### ISSUE TITLE
Invalid _next URL when upgrading from 0.5.8-alpha.3 to 0.7.0

### ISSUE THREAD

**Issue by khaeransori** [traveloka/soya-next#153]
**Describe the bug**
I set my config as below `"basePath": { "test": "/v2", "exclude": "/healthcheck" },`
on 0.5.8-alpha.3, I go `https://hnet.traveloka.dev/v2/_next` but after I upgrade into 0.7.0 I got this url
`https://hnet.traveloka.dev/_next/static/development/dll/dll_849f3a4f6ef9d4fb8cda.js`, without `v2` prefix

**To Reproduce**
1. add basePath config
2. Upgrade to 0.7.0
3. See the url loaded on console

**Expected behavior**
_next endpoint should prefixed with `basePath`

**Comment by sayuti-daniel** [comment]
Fixed in [v0.7.4](https://github.com/traveloka/soya-next/releases/tag/v0.7.4)
