### ISSUE TITLE
soya-next-scripts dev failed when update to v0.7.4

### ISSUE THREAD

**Issue by jeffryang24** [traveloka/soya-next#164]
**Describe the bug**
Soya next app could not run in development environment after upgrading to v0.7.4

**To Reproduce**
1. upgrade `soya-next-cli` to v0.7.4 (`yarn global upgrade soya-next-cli --latest`)
2. run `soya-next-cli test`.
3. `cd test` and run `yarn dev`.

**Expected behavior**
App should run joyfully.

**Screenshots**
![selection_001](https://user-images.githubusercontent.com/8284757/49686730-4be0f680-fb2b-11e8-9a0e-b91cde4a4e1c.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 70

**Comment by sayuti-daniel** [comment]
Please upgrade soya-next-scripts and soya-next-server to [v0.7.5](https://github.com/traveloka/soya-next/releases/tag/v0.7.5)
