### ISSUE TITLE
Error: Cannot find module '@babel/runtime-corejs2/helpers/interopRequireDefault'

### ISSUE THREAD

**Issue by geekyme** [traveloka/soya-next#229]
**Describe the bug**
Error: Cannot find module '@babel/runtime-corejs2/helpers/interopRequireDefault'

**To Reproduce**
1. `npm install -g soya-next-cli`
2. `soya-next-cli tutorial-soya`

**Expected behavior**
Should not have any missing dependency error

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: N/A
 - Version: latest

**Additional context**
node - v12.5.0
npm - 6.9.0

**Comment by sayuti-daniel** [comment]
Fixed in https://github.com/traveloka/soya-next/commit/07c6a94d4bd1f3fa3cc16c353044918c190e0827
