### ISSUE TITLE
Error: Cannot find module 'htmlescape'

### ISSUE THREAD

**Issue by geekyme** [traveloka/soya-next#242]
**Describe the bug**

Error: Cannot find module 'htmlescape'

**To Reproduce**
1. `npm install -g soya-next-cli`
2. `soya-next-cli path/to/app`
3. `cd path/to/app`
4. `npm run dev`
5. Visit `http://localhost:3000`

**Expected behavior**

Should not have this exception.

Problem goes away once I add the dependency myself - `npm install --save htmlescape`

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: Latest

**Additional context**

node version: v10.16.0
npm version: 6.9.0

**Comment by sayuti-daniel** [comment]
which soya-next-scripts version do you use? this has been fixed 2 months ago. https://github.com/traveloka/soya-next/commit/2f05613af9a06df341f9cae8892dd6f5244c079a

**Comment by sayuti-daniel** [comment]
we need to bump this version, can you help to submit a PR?
https://github.com/traveloka/soya-next/blob/3df7fb525b888049435b3e4b41dcd6bb329cb8d4/packages/soya-next-cli/src/index.js#L42-L46
