### ISSUE TITLE
[soya-next-scripts] Security vulnerability in webpack-bundle-analyzer

### ISSUE THREAD

**Issue by raibima** [traveloka/soya-next#255]
**Describe the bug**
I'm getting github alert about security vulnerability in webpack-bundle-analyzer. Running `yarn why webpack-bundle-analyzer` gives me this output:
```
=> Found "webpack-bundle-analyzer@2.13.1"
info Reasons this module exists
   - "soya-next-scripts#@zeit#next-bundle-analyzer" depends on it
   - Hoisted from "soya-next-scripts#@zeit#next-bundle-analyzer#webpack-bundle-analyzer"
```

After some digging, I found out that the `@zeit/next-bundle-analyzer` is no longer maintained and that we should instead use `@next/bundle-analyzer`.

Source: https://github.com/zeit/next-plugins/tree/master/packages/next-bundle-analyzer#nextjs--webpack-bundle-analyzer
Issue: https://github.com/zeit/next-plugins/issues/516

**To Reproduce**
Clone https://github.com/traveloka/toolsfe-flight repo and run `yarn audit` or `npm audit`

**Comment by angga-tvlk** [comment]
Close by #266
